import { SchemaType, SchemaTemplate, SelectOption } from '@/types/schema-markup'

// Common select options
export const countryOptions: SelectOption[] = [
  { value: 'NL', label: 'Nederland' },
  { value: 'BE', label: 'België' },
  { value: 'DE', label: 'Duitsland' },
  { value: 'FR', label: 'Frankrijk' },
  { value: 'GB', label: 'Verenigd Koninkrijk' },
  { value: 'US', label: 'Verenigde Staten' },
]

export const currencyOptions: SelectOption[] = [
  { value: 'EUR', label: 'EUR (€)' },
  { value: 'USD', label: 'USD ($)' },
  { value: 'GBP', label: 'GBP (£)' },
]

export const availabilityOptions: SelectOption[] = [
  { value: 'https://schema.org/InStock', label: 'Op voorraad' },
  { value: 'https://schema.org/OutOfStock', label: 'Niet op voorraad' },
  { value: 'https://schema.org/PreOrder', label: 'Pre-order' },
  { value: 'https://schema.org/BackOrder', label: 'Nabestelling' },
  { value: 'https://schema.org/LimitedAvailability', label: 'Beperkt beschikbaar' },
]

export const dayOfWeekOptions: SelectOption[] = [
  { value: 'Monday', label: 'Maandag' },
  { value: 'Tuesday', label: 'Dinsdag' },
  { value: 'Wednesday', label: 'Woensdag' },
  { value: 'Thursday', label: 'Donderdag' },
  { value: 'Friday', label: 'Vrijdag' },
  { value: 'Saturday', label: 'Zaterdag' },
  { value: 'Sunday', label: 'Zondag' },
]

export const priceRangeOptions: SelectOption[] = [
  { value: '€', label: '€ - Goedkoop' },
  { value: '€€', label: '€€ - Gemiddeld' },
  { value: '€€€', label: '€€€ - Duur' },
  { value: '€€€€', label: '€€€€ - Zeer duur' },
]

export const eventStatusOptions: SelectOption[] = [
  { value: 'https://schema.org/EventScheduled', label: 'Gepland' },
  { value: 'https://schema.org/EventCancelled', label: 'Geannuleerd' },
  { value: 'https://schema.org/EventPostponed', label: 'Uitgesteld' },
  { value: 'https://schema.org/EventRescheduled', label: 'Verplaatst' },
]

// Schema Templates
export const schemaTemplates: Record<SchemaType, SchemaTemplate> = {
  [SchemaType.Organization]: {
    type: SchemaType.Organization,
    label: 'Organisatie',
    description: 'Bedrijf of organisatie met contactgegevens en logo',
    icon: 'Building2',
    properties: [
      {
        name: 'name',
        label: 'Organisatienaam',
        type: 'text',
        required: true,
        placeholder: 'Bijv. Acme B.V.',
      },
      {
        name: 'url',
        label: 'Website URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl',
      },
      {
        name: 'logo',
        label: 'Logo URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl/logo.png',
        description: 'URL naar het logo (minimaal 112x112 pixels)',
      },
      {
        name: 'description',
        label: 'Beschrijving',
        type: 'textarea',
        required: false,
        placeholder: 'Korte beschrijving van de organisatie...',
      },
      {
        name: 'email',
        label: 'E-mailadres',
        type: 'text',
        required: false,
        placeholder: 'info@voorbeeld.nl',
      },
      {
        name: 'telephone',
        label: 'Telefoonnummer',
        type: 'text',
        required: false,
        placeholder: '+31 20 123 4567',
      },
      {
        name: 'streetAddress',
        label: 'Straat en huisnummer',
        type: 'text',
        required: false,
        placeholder: 'Voorbeeldstraat 123',
      },
      {
        name: 'addressLocality',
        label: 'Plaats',
        type: 'text',
        required: false,
        placeholder: 'Amsterdam',
      },
      {
        name: 'postalCode',
        label: 'Postcode',
        type: 'text',
        required: false,
        placeholder: '1234 AB',
      },
      {
        name: 'addressCountry',
        label: 'Land',
        type: 'select',
        required: false,
        options: countryOptions,
      },
      {
        name: 'sameAs',
        label: 'Social media links',
        type: 'array',
        required: false,
        arrayItemType: 'url',
        placeholder: 'https://www.linkedin.com/company/voorbeeld',
        description: 'Voeg links toe naar social media profielen',
      },
    ],
    requiredGoogleFields: ['name', 'url', 'logo'],
    recommendedFields: ['description', 'telephone', 'sameAs'],
  },

  [SchemaType.LocalBusiness]: {
    type: SchemaType.LocalBusiness,
    label: 'Lokaal Bedrijf',
    description: 'Fysiek bedrijf met adres en openingstijden',
    icon: 'Store',
    properties: [
      {
        name: 'name',
        label: 'Bedrijfsnaam',
        type: 'text',
        required: true,
        placeholder: 'Bijv. Restaurant De Gouden Lepel',
      },
      {
        name: 'url',
        label: 'Website URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl',
      },
      {
        name: 'image',
        label: 'Afbeelding URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl/foto.jpg',
      },
      {
        name: 'telephone',
        label: 'Telefoonnummer',
        type: 'text',
        required: true,
        placeholder: '+31 20 123 4567',
      },
      {
        name: 'streetAddress',
        label: 'Straat en huisnummer',
        type: 'text',
        required: true,
        placeholder: 'Voorbeeldstraat 123',
      },
      {
        name: 'addressLocality',
        label: 'Plaats',
        type: 'text',
        required: true,
        placeholder: 'Amsterdam',
      },
      {
        name: 'postalCode',
        label: 'Postcode',
        type: 'text',
        required: true,
        placeholder: '1234 AB',
      },
      {
        name: 'addressCountry',
        label: 'Land',
        type: 'select',
        required: true,
        options: countryOptions,
        defaultValue: 'NL',
      },
      {
        name: 'priceRange',
        label: 'Prijsklasse',
        type: 'select',
        required: false,
        options: priceRangeOptions,
      },
      {
        name: 'description',
        label: 'Beschrijving',
        type: 'textarea',
        required: false,
        placeholder: 'Korte beschrijving van het bedrijf...',
      },
      {
        name: 'openingHours',
        label: 'Openingstijden',
        type: 'repeatable-group',
        required: false,
        description: 'Voeg openingstijden toe per dag of daggroep',
        groupFields: [
          {
            name: 'dayOfWeek',
            label: 'Dag(en)',
            type: 'select',
            required: true,
            options: dayOfWeekOptions,
          },
          {
            name: 'opens',
            label: 'Opent',
            type: 'text',
            required: true,
            placeholder: '09:00',
          },
          {
            name: 'closes',
            label: 'Sluit',
            type: 'text',
            required: true,
            placeholder: '17:00',
          },
        ],
      },
      {
        name: 'latitude',
        label: 'Breedtegraad (latitude)',
        type: 'text',
        required: false,
        placeholder: '52.3676',
      },
      {
        name: 'longitude',
        label: 'Lengtegraad (longitude)',
        type: 'text',
        required: false,
        placeholder: '4.9041',
      },
    ],
    requiredGoogleFields: ['name', 'streetAddress', 'addressLocality'],
    recommendedFields: ['telephone', 'openingHours', 'priceRange'],
  },

  [SchemaType.Product]: {
    type: SchemaType.Product,
    label: 'Product',
    description: 'E-commerce product met prijs en beschikbaarheid',
    icon: 'ShoppingBag',
    properties: [
      {
        name: 'name',
        label: 'Productnaam',
        type: 'text',
        required: true,
        placeholder: 'Bijv. Ergonomische bureaustoel',
      },
      {
        name: 'image',
        label: 'Product afbeelding URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl/product.jpg',
      },
      {
        name: 'description',
        label: 'Productbeschrijving',
        type: 'textarea',
        required: true,
        placeholder: 'Gedetailleerde beschrijving van het product...',
      },
      {
        name: 'sku',
        label: 'SKU / Artikelnummer',
        type: 'text',
        required: false,
        placeholder: 'ABC-12345',
      },
      {
        name: 'brand',
        label: 'Merknaam',
        type: 'text',
        required: false,
        placeholder: 'Bijv. Nike',
      },
      {
        name: 'price',
        label: 'Prijs',
        type: 'number',
        required: true,
        placeholder: '99.99',
      },
      {
        name: 'priceCurrency',
        label: 'Valuta',
        type: 'select',
        required: true,
        options: currencyOptions,
        defaultValue: 'EUR',
      },
      {
        name: 'availability',
        label: 'Beschikbaarheid',
        type: 'select',
        required: true,
        options: availabilityOptions,
        defaultValue: 'https://schema.org/InStock',
      },
      {
        name: 'url',
        label: 'Product URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/product/bureaustoel',
      },
      {
        name: 'ratingValue',
        label: 'Gemiddelde beoordeling',
        type: 'number',
        required: false,
        placeholder: '4.5',
        description: 'Waarde tussen 1 en 5',
      },
      {
        name: 'reviewCount',
        label: 'Aantal reviews',
        type: 'number',
        required: false,
        placeholder: '127',
      },
    ],
    requiredGoogleFields: ['name', 'image', 'price', 'priceCurrency'],
    recommendedFields: ['description', 'availability', 'brand', 'sku'],
  },

  [SchemaType.Article]: {
    type: SchemaType.Article,
    label: 'Artikel',
    description: 'Blog post, nieuwsartikel of andere content',
    icon: 'FileText',
    properties: [
      {
        name: 'headline',
        label: 'Titel',
        type: 'text',
        required: true,
        placeholder: 'De titel van het artikel',
        description: 'Maximaal 110 tekens aanbevolen',
      },
      {
        name: 'image',
        label: 'Afbeelding URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl/artikel-afbeelding.jpg',
        description: 'Minimaal 1200 pixels breed aanbevolen',
      },
      {
        name: 'datePublished',
        label: 'Publicatiedatum',
        type: 'datetime',
        required: true,
        placeholder: '2024-01-15T10:00:00+01:00',
      },
      {
        name: 'dateModified',
        label: 'Laatst gewijzigd',
        type: 'datetime',
        required: false,
        placeholder: '2024-01-20T14:30:00+01:00',
      },
      {
        name: 'authorName',
        label: 'Auteur naam',
        type: 'text',
        required: true,
        placeholder: 'Jan Jansen',
      },
      {
        name: 'authorUrl',
        label: 'Auteur profiel URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/team/jan-jansen',
      },
      {
        name: 'publisherName',
        label: 'Uitgever naam',
        type: 'text',
        required: true,
        placeholder: 'Voorbeeld Media B.V.',
      },
      {
        name: 'publisherLogo',
        label: 'Uitgever logo URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl/logo.png',
      },
      {
        name: 'description',
        label: 'Beschrijving / samenvatting',
        type: 'textarea',
        required: false,
        placeholder: 'Een korte samenvatting van het artikel...',
      },
    ],
    requiredGoogleFields: ['headline', 'image', 'datePublished', 'authorName', 'publisherName', 'publisherLogo'],
    recommendedFields: ['description', 'dateModified'],
  },

  [SchemaType.FAQPage]: {
    type: SchemaType.FAQPage,
    label: 'FAQ Pagina',
    description: 'Veelgestelde vragen met antwoorden',
    icon: 'HelpCircle',
    properties: [
      {
        name: 'items',
        label: 'Vragen en antwoorden',
        type: 'repeatable-group',
        required: true,
        description: 'Voeg minimaal 2 vragen toe',
        groupFields: [
          {
            name: 'question',
            label: 'Vraag',
            type: 'text',
            required: true,
            placeholder: 'Wat is de levertijd?',
          },
          {
            name: 'answer',
            label: 'Antwoord',
            type: 'textarea',
            required: true,
            placeholder: 'De standaard levertijd is 2-3 werkdagen...',
          },
        ],
      },
    ],
    requiredGoogleFields: ['items'],
  },

  [SchemaType.BreadcrumbList]: {
    type: SchemaType.BreadcrumbList,
    label: 'Breadcrumbs',
    description: 'Navigatiepad voor betere zoekresultaten',
    icon: 'ChevronRight',
    properties: [
      {
        name: 'items',
        label: 'Breadcrumb items',
        type: 'repeatable-group',
        required: true,
        description: 'Voeg breadcrumb items toe in volgorde (home → categorie → pagina)',
        groupFields: [
          {
            name: 'name',
            label: 'Naam',
            type: 'text',
            required: true,
            placeholder: 'Home',
          },
          {
            name: 'url',
            label: 'URL',
            type: 'url',
            required: true,
            placeholder: 'https://www.voorbeeld.nl/',
          },
        ],
      },
    ],
    requiredGoogleFields: ['items'],
  },

  [SchemaType.HowTo]: {
    type: SchemaType.HowTo,
    label: 'How-To / Handleiding',
    description: 'Stapsgewijze instructies voor een taak',
    icon: 'ListChecks',
    properties: [
      {
        name: 'name',
        label: 'Titel',
        type: 'text',
        required: true,
        placeholder: 'Hoe maak je een taart',
      },
      {
        name: 'description',
        label: 'Beschrijving',
        type: 'textarea',
        required: true,
        placeholder: 'In deze handleiding leer je stap voor stap...',
      },
      {
        name: 'image',
        label: 'Afbeelding URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/handleiding.jpg',
      },
      {
        name: 'totalTime',
        label: 'Totale tijd (ISO 8601)',
        type: 'text',
        required: false,
        placeholder: 'PT1H30M',
        description: 'Bijv. PT1H30M voor 1 uur en 30 minuten',
      },
      {
        name: 'estimatedCost',
        label: 'Geschatte kosten',
        type: 'text',
        required: false,
        placeholder: '€25',
      },
      {
        name: 'steps',
        label: 'Stappen',
        type: 'repeatable-group',
        required: true,
        description: 'Voeg de stappen toe in chronologische volgorde',
        groupFields: [
          {
            name: 'name',
            label: 'Stap titel',
            type: 'text',
            required: true,
            placeholder: 'Verwarm de oven voor',
          },
          {
            name: 'text',
            label: 'Instructie',
            type: 'textarea',
            required: true,
            placeholder: 'Zet de oven op 180 graden Celsius...',
          },
          {
            name: 'image',
            label: 'Stap afbeelding URL',
            type: 'url',
            required: false,
            placeholder: 'https://www.voorbeeld.nl/stap1.jpg',
          },
        ],
      },
    ],
    requiredGoogleFields: ['name', 'steps'],
    recommendedFields: ['description', 'image', 'totalTime'],
  },

  [SchemaType.Event]: {
    type: SchemaType.Event,
    label: 'Evenement',
    description: 'Concert, workshop, conferentie of ander evenement',
    icon: 'Calendar',
    properties: [
      {
        name: 'name',
        label: 'Evenement naam',
        type: 'text',
        required: true,
        placeholder: 'Marketing Summit 2024',
      },
      {
        name: 'description',
        label: 'Beschrijving',
        type: 'textarea',
        required: true,
        placeholder: 'Beschrijving van het evenement...',
      },
      {
        name: 'startDate',
        label: 'Startdatum en -tijd',
        type: 'datetime',
        required: true,
        placeholder: '2024-06-15T09:00:00+02:00',
      },
      {
        name: 'endDate',
        label: 'Einddatum en -tijd',
        type: 'datetime',
        required: false,
        placeholder: '2024-06-15T17:00:00+02:00',
      },
      {
        name: 'eventStatus',
        label: 'Status',
        type: 'select',
        required: false,
        options: eventStatusOptions,
        defaultValue: 'https://schema.org/EventScheduled',
      },
      {
        name: 'location',
        label: 'Locatie naam',
        type: 'text',
        required: true,
        placeholder: 'RAI Amsterdam',
      },
      {
        name: 'locationAddress',
        label: 'Locatie adres',
        type: 'text',
        required: false,
        placeholder: 'Europaplein 24, 1078 GZ Amsterdam',
      },
      {
        name: 'image',
        label: 'Evenement afbeelding URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/event.jpg',
      },
      {
        name: 'url',
        label: 'Evenement URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/events/marketing-summit',
      },
      {
        name: 'performerName',
        label: 'Artiest / Spreker',
        type: 'text',
        required: false,
        placeholder: 'Jan Jansen',
      },
      {
        name: 'organizerName',
        label: 'Organisator',
        type: 'text',
        required: false,
        placeholder: 'Voorbeeld Events B.V.',
      },
      {
        name: 'price',
        label: 'Ticketprijs',
        type: 'number',
        required: false,
        placeholder: '49.99',
      },
      {
        name: 'priceCurrency',
        label: 'Valuta',
        type: 'select',
        required: false,
        options: currencyOptions,
        defaultValue: 'EUR',
      },
      {
        name: 'availability',
        label: 'Ticket beschikbaarheid',
        type: 'select',
        required: false,
        options: availabilityOptions,
      },
    ],
    requiredGoogleFields: ['name', 'startDate', 'location'],
    recommendedFields: ['description', 'image', 'endDate', 'url'],
  },

  [SchemaType.Person]: {
    type: SchemaType.Person,
    label: 'Persoon',
    description: 'Profiel van een persoon of team member',
    icon: 'User',
    properties: [
      {
        name: 'name',
        label: 'Volledige naam',
        type: 'text',
        required: true,
        placeholder: 'Jan Jansen',
      },
      {
        name: 'url',
        label: 'Profiel URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/team/jan-jansen',
      },
      {
        name: 'image',
        label: 'Foto URL',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/team/jan-jansen.jpg',
      },
      {
        name: 'jobTitle',
        label: 'Functietitel',
        type: 'text',
        required: false,
        placeholder: 'Marketing Manager',
      },
      {
        name: 'worksFor',
        label: 'Werkgever',
        type: 'text',
        required: false,
        placeholder: 'Voorbeeld B.V.',
      },
      {
        name: 'email',
        label: 'E-mailadres',
        type: 'text',
        required: false,
        placeholder: 'jan@voorbeeld.nl',
      },
      {
        name: 'telephone',
        label: 'Telefoonnummer',
        type: 'text',
        required: false,
        placeholder: '+31 6 12345678',
      },
      {
        name: 'sameAs',
        label: 'Social media links',
        type: 'array',
        required: false,
        arrayItemType: 'url',
        placeholder: 'https://www.linkedin.com/in/janjansen',
      },
    ],
    requiredGoogleFields: ['name'],
    recommendedFields: ['image', 'jobTitle', 'worksFor'],
  },

  [SchemaType.WebSite]: {
    type: SchemaType.WebSite,
    label: 'Website',
    description: 'Website met zoekvak voor sitelinks',
    icon: 'Globe',
    properties: [
      {
        name: 'name',
        label: 'Website naam',
        type: 'text',
        required: true,
        placeholder: 'Voorbeeld.nl',
      },
      {
        name: 'url',
        label: 'Website URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl',
      },
      {
        name: 'searchUrl',
        label: 'Zoek URL (voor sitelinks searchbox)',
        type: 'url',
        required: false,
        placeholder: 'https://www.voorbeeld.nl/zoeken?q={search_term_string}',
        description: 'Gebruik {search_term_string} als placeholder voor de zoekterm',
      },
    ],
    requiredGoogleFields: ['name', 'url'],
    recommendedFields: ['searchUrl'],
  },

  [SchemaType.Recipe]: {
    type: SchemaType.Recipe,
    label: 'Recept',
    description: 'Kookrecept met ingrediënten en instructies',
    icon: 'ChefHat',
    properties: [
      {
        name: 'name',
        label: 'Recept naam',
        type: 'text',
        required: true,
        placeholder: 'Klassieke appeltaart',
      },
      {
        name: 'image',
        label: 'Recept afbeelding URL',
        type: 'url',
        required: true,
        placeholder: 'https://www.voorbeeld.nl/appeltaart.jpg',
      },
      {
        name: 'description',
        label: 'Beschrijving',
        type: 'textarea',
        required: true,
        placeholder: 'Een heerlijke klassieke appeltaart met knapperig deeg...',
      },
      {
        name: 'prepTime',
        label: 'Bereidingstijd (ISO 8601)',
        type: 'text',
        required: false,
        placeholder: 'PT30M',
        description: 'Bijv. PT30M voor 30 minuten',
      },
      {
        name: 'cookTime',
        label: 'Baktijd (ISO 8601)',
        type: 'text',
        required: false,
        placeholder: 'PT1H',
        description: 'Bijv. PT1H voor 1 uur',
      },
      {
        name: 'totalTime',
        label: 'Totale tijd (ISO 8601)',
        type: 'text',
        required: false,
        placeholder: 'PT1H30M',
      },
      {
        name: 'recipeYield',
        label: 'Aantal porties',
        type: 'text',
        required: false,
        placeholder: '8 porties',
      },
      {
        name: 'recipeIngredient',
        label: 'Ingrediënten',
        type: 'array',
        required: true,
        arrayItemType: 'text',
        placeholder: '500g bloem',
        description: 'Voeg elk ingrediënt apart toe',
      },
      {
        name: 'recipeInstructions',
        label: 'Bereidingsstappen',
        type: 'repeatable-group',
        required: true,
        groupFields: [
          {
            name: 'text',
            label: 'Instructie',
            type: 'textarea',
            required: true,
            placeholder: 'Meng de bloem met de boter tot een kruimelig deeg...',
          },
        ],
      },
      {
        name: 'authorName',
        label: 'Auteur',
        type: 'text',
        required: false,
        placeholder: 'Chef Jan',
      },
      {
        name: 'ratingValue',
        label: 'Gemiddelde beoordeling',
        type: 'number',
        required: false,
        placeholder: '4.8',
      },
      {
        name: 'reviewCount',
        label: 'Aantal reviews',
        type: 'number',
        required: false,
        placeholder: '256',
      },
    ],
    requiredGoogleFields: ['name', 'image', 'recipeIngredient', 'recipeInstructions'],
    recommendedFields: ['description', 'prepTime', 'cookTime', 'ratingValue'],
  },

  [SchemaType.Review]: {
    type: SchemaType.Review,
    label: 'Review',
    description: 'Beoordeling van een product, service of bedrijf',
    icon: 'Star',
    properties: [
      {
        name: 'itemReviewedName',
        label: 'Beoordeeld item naam',
        type: 'text',
        required: true,
        placeholder: 'iPhone 15 Pro',
      },
      {
        name: 'itemReviewedType',
        label: 'Type item',
        type: 'select',
        required: true,
        options: [
          { value: 'Product', label: 'Product' },
          { value: 'LocalBusiness', label: 'Lokaal bedrijf' },
          { value: 'Organization', label: 'Organisatie' },
          { value: 'Book', label: 'Boek' },
          { value: 'Movie', label: 'Film' },
          { value: 'Restaurant', label: 'Restaurant' },
        ],
      },
      {
        name: 'reviewBody',
        label: 'Review tekst',
        type: 'textarea',
        required: true,
        placeholder: 'Een uitgebreide review van het product...',
      },
      {
        name: 'ratingValue',
        label: 'Beoordeling',
        type: 'number',
        required: true,
        placeholder: '4.5',
        description: 'Waarde tussen 1 en 5',
      },
      {
        name: 'bestRating',
        label: 'Maximale score',
        type: 'number',
        required: false,
        placeholder: '5',
        defaultValue: '5',
      },
      {
        name: 'worstRating',
        label: 'Minimale score',
        type: 'number',
        required: false,
        placeholder: '1',
        defaultValue: '1',
      },
      {
        name: 'authorName',
        label: 'Reviewer naam',
        type: 'text',
        required: true,
        placeholder: 'Jan Jansen',
      },
      {
        name: 'datePublished',
        label: 'Review datum',
        type: 'date',
        required: false,
        placeholder: '2024-01-15',
      },
      {
        name: 'publisherName',
        label: 'Uitgever naam',
        type: 'text',
        required: false,
        placeholder: 'Tech Reviews NL',
      },
    ],
    requiredGoogleFields: ['itemReviewedName', 'ratingValue', 'authorName'],
    recommendedFields: ['reviewBody', 'datePublished'],
  },
}

export function getSchemaTemplate(type: SchemaType): SchemaTemplate {
  return schemaTemplates[type]
}

export function getAllSchemaTypes(): SchemaType[] {
  return Object.values(SchemaType)
}

export function getSchemaTypeInfo(type: SchemaType): { label: string; description: string; icon: string } {
  const template = schemaTemplates[type]
  return {
    label: template.label,
    description: template.description,
    icon: template.icon,
  }
}
